#Task 1 :Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library).

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43], 
                    [91, 88, 64], 
                    [87, 134, 58], 
                    [102, 43, 37], 
                    [69, 96, 70]], dtype='float32')
print(inputs.shape)

(15, 3)


In [ ]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.4, random_state=71)

In [ ]:
reg = LinearRegression().fit(x_train,y_train)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [ ]:
print(reg.intercept_)
print(reg.coef_)

[ 0.36309052 -2.3584595 ]
[[-0.39352015  0.8542148   0.66008997]
 [-0.28474173  0.79355395  0.9276447 ]]


In [ ]:
y_pred = reg.predict(x_test)
print(y_pred,"\n")
print(y_test)

[[ 21.378601  37.043556]
 [ 57.25238   69.91223 ]
 [ 81.96941  100.93205 ]
 [101.42112  119.11067 ]
 [101.42112  119.11067 ]
 [ 57.25238   69.91223 ]] 

[[ 22.  37.]
 [ 56.  70.]
 [ 81. 101.]
 [103. 119.]
 [103. 119.]
 [ 56.  70.]]


In [ ]:
from sklearn import metrics
print('\n Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))


 Mean Squared Error: 0.79124635
