#Task2: Try Linear regression on same prediction data using Tensorflow

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [ ]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [ ]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.61996314, 0.02055047],
       [0.47205264, 0.2113395 ],
       [0.08255982, 0.49380304]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([ 2.08719798, -0.80325917])>


In [ ]:
def model(s):
    return s @ v + r

In [ ]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 82.52210619  36.09020233]
 [105.32830435  51.26810409]
 [124.06751434  57.94470121]
 [ 88.67641484  28.65119959]
 [ 95.96089541  55.46952804]
 [ 82.52210619  36.09020233]
 [105.32830435  51.26810409]
 [124.06751434  57.94470121]
 [ 88.67641484  28.65119959]
 [ 95.96089541  55.46952804]
 [ 82.52210619  36.09020233]
 [105.32830435  51.26810409]
 [124.06751434  57.94470121]
 [ 88.67641484  28.65119959]
 [ 95.96089541  55.46952804]], shape=(15, 2), dtype=float64)


In [ ]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(1917.851856013615, shape=(), dtype=float64)


In [ ]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 1917.851856013615
 
 Epoch count: 1 
 Loss value: 1332.9977598690025
 
 Epoch count: 2 
 Loss value: 951.5855106192688
 
 Epoch count: 3 
 Loss value: 699.3360717038879
 
 Epoch count: 4 
 Loss value: 529.549160388819
 
 Epoch count: 5 
 Loss value: 412.8060575871813
 
 Epoch count: 6 
 Loss value: 330.52424273634654
 
 Epoch count: 7 
 Loss value: 270.9221423517669
 
 Epoch count: 8 
 Loss value: 226.49201098592033
 
 Epoch count: 9 
 Loss value: 192.41662273795237
 
 Epoch count: 10 
 Loss value: 165.57669547591337
 
 Epoch count: 11 
 Loss value: 143.92812829107234
 
 Epoch count: 12 
 Loss value: 126.11081478393263
 
 Epoch count: 13 
 Loss value: 111.20252416870865
 
 Epoch count: 14 
 Loss value: 98.56370722245599
 
 Epoch count: 15 
 Loss value: 87.73933447634911
 
 Epoch count: 16 
 Loss value: 78.39654517047595
 
 Epoch count: 17 
 Loss value: 70.28481475504684
 
 Epoch count: 18 
 Loss value: 63.210311215530574
 
 Epoch count: 19 
 Loss value: 